# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('nickname', models.CharField(default='一位不愿透露姓名的勇士', max_length=20, verbose_name='昵称')),
                ('message', models.TextField(verbose_name='内容/消息')),
                ('del_pass', models.CharField(default=123456, max_length=10)),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否呈现出来')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='选择类型')),
            ],
        ),
        migrations.AddField(
            model_name='matter',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_objects.Mood', verbose_name='选择心情'),
        ),
    ]
